### ISSUE TITLE
createlang removed in postgresql 10.x

### ISSUE THREAD

**Issue by sabman** [sabman/cartodb-docker-fork#12]
createlang utility has been removed from postgresql 10.x
use `CREATE EXTENSION` instead. see:

- https://www.postgresql.org/docs/9.6/sql-createlanguage.html
- https://www.postgresql.org/docs/9.6/app-createlang.html

**Comment by sindile** [comment]
It looks like this line is not required
psql -U $PGUSER template_postgis -c "CREATE EXTENSION plpgsql;"
As it leads to an error the plpgsql already exist, with both postgis and resque containers having a state of Exit 1
Commenting out the psql -U $PGUSER template_postgis -c "CREATE EXTENSION plpgsql;" seems to solve the problem

**Comment by sabman** [comment]
Thanks @sindile I'll take a look
