### ISSUE TITLE
Analysis/Batch API Failing

### ISSUE THREAD

**Issue by sabman** [sabman/cartodb-docker-fork#16]
in the analysis logs I am seeing:

```json
{  
  "name":"camshaft",
  "hostname":"a11804d63940",
  "pid":1,
  "level":30,
  "msg":"analysis:limits_error",
  "time":"2019-02-19T16:52:08.563Z",
  "v":0
}
```
saw something similar in #3

**Comment by nballenger** [comment]
I haven't experienced this personally, but it looks like you're hitting a per user or per org limit that's set in the metadata database. The issue is closed so presumably you solved it, but if it was me I'd be looking at the rake tasks that update settings, like `rake cartodb:db:set_unlimited_table_quota`. 

@sabman - If you get time, I'd be interested to know what your resolution turned out to be.

**Comment by sabman** [comment]
@nballenger thanks for the tip I think it was something like that.

**Comment by sabman** [comment]
@nballenger how are you going? I wanted to let you know since we have been running carto in production in a microservices environment (think docker, docker swarm and kubernetes) with backups and monitoring for our clients. 

After going through the pain of setting up carto in a high performance and high availability environment we have decided to make our solution available as a service and are happy to announce the launch of http://cartohost.com 

We are still in beta an sign up still requires some manual setups. 

Ping me if you wanna talk more.

Shoaib Burq
--
CTO SpacialDB UG, Berlin
twitter.com/sabman

**Comment by nballenger** [comment]
Hi, @sabman -- this looks really interesting. The project I'm working on (which I think you saw, maybe) is at:

https://github.com/ruralinnovation/multi-svc-cartodb

I'm consulting for a client interested in self-hosting Carto, and given the level of frustration I've seen generally with doing that, I've been working on putting together some open source ops documentation around running multi-container Carto for HA / production.

I'd love to chat some time--just sent you a message on LinkedIn with my contact info.

Nick

**Comment by nballenger** [comment]
@sabman FYI, turns out it's not an analysis limits thing at all, not sure if you resolved it, but looks like it's that the geocoder isn't ready:

https://github.com/CartoDB/camshaft/issues/365
